import cv2
import smtplib
# import the corresponding modules
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

#initialise variables, lists and dataframes
FirstFrame = None
fourcc = cv2.VideoWriter_fourcc(*'XVID')
#Start Capturing on Webcam
cap = cv2.VideoCapture(0)
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640,480))
while(True):
    # Capture frame-by-frame
    check, Color_frame = cap.read()    
    # Our operations on the frame come here
    Color_frame = cv2.flip(Color_frame, 1)
    status = 0
    #convert to Gray
    gray = cv2.cvtColor(Color_frame, cv2.COLOR_BGR2GRAY)
    #Introduce Gaussian Blur to remove noise
    gray = cv2.GaussianBlur(gray, (21,21), 0)
    #Capture First Frame, as it will be compared with rest
    if FirstFrame is None:
        FirstFrame = gray
        continue
    DeltaFrame = cv2.absdiff(FirstFrame, gray)
    ThreshFrame = cv2.threshold(DeltaFrame, 30, 255, cv2.THRESH_BINARY)[1]
    #Dilate the Threshold Frame
    ThreshFrame = cv2.dilate(ThreshFrame, None, iterations = 3)
    (cnts, _) = cv2.findContours(ThreshFrame.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in cnts:
        if cv2.contourArea(contour)<10000:
            continue
        status = 1
        (x,y,w,h) = cv2.boundingRect(contour)
        AllFrame = cv2.rectangle(Color_frame, (x,y), (x+w,y+h), (0,0,255), 2)
        out.write(AllFrame)
    cv2.imshow("Colour Frame", Color_frame)
    #cv2.imshow("Grey Frame", gray)
    #cv2.imshow("Delta Frame", DeltaFrame)
    #cv2.imshow("Threshold Frame", ThreshFrame)
    
    key = cv2.waitKey(1)
    if key == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
    
    
# send your email
port = 2525 
smtp_server = "smtp.mailtrap.io"
login = "23ebfd20ff9746" # paste your login generated by Mailtrap
password = "ba6f178c198086" # paste your password generated by Mailtrap

subject = "Motion Detected"
sender_email = "shabarish033@gmail.com"
receiver_email = "shabarishpilkunravi@gmail.com"

message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

# Add body to email
body = "Hey there is some motion detected in your apartment"
message.attach(MIMEText(body, "plain"))

filename = "output.avi"
# Open file in binary mode
# We assume that the file is in the directory where you run your Python script from
with open(filename, "rb") as attachment:
    # The content type "application/octet-stream" means that a MIME attachment is a binary file
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())

# Encode to base64
encoders.encode_base64(part)
# Add header 
part.add_header(
    "Content-Disposition",
    f"attachment; filename= {filename}",
)

# Add attachment to your message and convert it to string
message.attach(part)
text = message.as_string()
with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
    server.login(login, password)
    server.sendmail(
        sender_email, receiver_email, text
    )
print('Sent')

        